spring:
  application:
    name: kf-imapi-auth-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:9091/realms/imapi
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9091/realms/imapi
        registration:
          keycloak:
            client-id: demo
            scope: openid
    # Recommended to use cache in production environment
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: maximumSize=100,expireAfterAccess=5m
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      database: 0
      lettuce:
        pool:
          max-active: 8 # Maximum number of connections that can be allocated by the pool at a given time
          max-idle: 8
          min-idle: 4

server:
  port: 8084
  
# ------------------------ OpenApi --------------------------
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#    try-it-out-enabled: true
#  api-docs:
#    path: /v3/api-docs
#  show-actuator: true

# ------------------------ Observability (Micrometer) --------------------------
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100%
  endpoints:
    web:
      exposure:
        include: prometheus

# ------------------------ Gateway --------------------------
gateway:
  # Configure it in a safe way like using a secret manager (K8s secrets, AWS Secrets Manager, etc)
  internal-auth-secret: 1234
  
# ------------------------ Eureka --------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# ------------------------ Logging ------------------------
logging:
  level:
    org.springframework.security: info # trace | debug | info | warn | error | fatal | off
    org.springframework.cloud.gateway: info
    org.springframework.boot: info
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

# ------------------------ Keycloak --------------------------
#keycloak:
#  auth-server-url: http://localhost:9091/auth
#  realm: kf-imapi-realm
#  resource: auth-gateway-keycloack
#  credentials:
#    secret: client-secret-aqui
#  public-client: false
#  security-constraints:
#    - authRoles:
#        - user
#      securityCollections:
#        - patterns:
#            - /api/*