spring:
  application:
    name: kf-imapi-auth-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:9091/realms/imapi
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9091/realms/imapi
        registration:
          keycloak:
            client-id: demo
            scope: openid
            
server:
  port: 8084
  
# ------------------------ Gateway --------------------------
gateway:
  # Configure it in a safe way like using a secret manager (K8s secrets, AWS Secrets Manager, etc)
  internal-auth-secret: 1234
  
# ------------------------ Eureka --------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# ------------------------ Logging ------------------------
logging:
  level:
    org.springframework.security: trace
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

# ------------------------ Keycloak --------------------------
#keycloak:
#  auth-server-url: http://localhost:9091/auth
#  realm: kf-imapi-realm
#  resource: auth-gateway-keycloack
#  credentials:
#    secret: client-secret-aqui
#  public-client: false
#  security-constraints:
#    - authRoles:
#        - user
#      securityCollections:
#        - patterns:
#            - /api/*